M48
; DRILL file {KiCad 9.0.1} date 2026-03-30T08:58:14-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-30T08:58:14-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1770
%
G90
G05
T1
X2.3598Y-1.15
X3.3098Y-1.15
T2
X1.375Y-5.8
X1.375Y-8.8
X7.0Y-1.2
X7.0Y-5.8
X7.0Y-8.8
X12.8Y-1.2
X12.8Y-8.8
M30
